### ISSUE TITLE
Add suport for Guzzle 7

### ISSUE THREAD

**Issue by sairam2188** [josiasmontag/laravel-recaptchav3#14]
Hi, please add support for the latest version of guzzlehttp/guzzle 7.0.1. I have Laravel 7 and PHP 7.3.21
I have this error in composer.

Using version ^0.5.0 for josiasmontag/laravel-recaptchav3
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for josiasmontag/laravel-recaptchav3 ^0.5.0 -> satisfiable by josiasmontag/laravel-recaptchav3[0.5.0].
    - Conclusion: remove guzzlehttp/guzzle 7.0.1
    - Conclusion: don't install guzzlehttp/guzzle 7.0.1
    - josiasmontag/laravel-recaptchav3 0.5.0 requires guzzlehttp/guzzle ^6.2 -> satisfiable by guzzlehttp/guzzle[6.2.0, 6.2.1, 6.2.2, 6.2.3, 6.3.0, 6.3.1, 6.3.2, 6.3.3, 6.4.0, 6.4.1, 6.5.0, 6.5.1, 6.5.2, 6.5.3, 6.5.4, 6.5.5].
    - Can only install one of: guzzlehttp/guzzle[6.2.0, 7.0.1].
    - Can only install one of: guzzlehttp/guzzle[6.2.1, 7.0.1].
    - Can only install one of: guzzlehttp/guzzle[6.2.2, 7.0.1].
    - Can only install one of: guzzlehttp/guzzle[6.2.3, 7.0.1].
    - Can only install one of: guzzlehttp/guzzle[6.3.0, 7.0.1].
    - Can only install one of: guzzlehttp/guzzle[6.3.1, 7.0.1].
    - Can only install one of: guzzlehttp/guzzle[6.3.2, 7.0.1].
    - Can only install one of: guzzlehttp/guzzle[6.3.3, 7.0.1].
    - Can only install one of: guzzlehttp/guzzle[6.4.0, 7.0.1].
    - Can only install one of: guzzlehttp/guzzle[6.4.1, 7.0.1].
    - Can only install one of: guzzlehttp/guzzle[6.5.0, 7.0.1].
    - Can only install one of: guzzlehttp/guzzle[6.5.1, 7.0.1].
    - Can only install one of: guzzlehttp/guzzle[6.5.2, 7.0.1].
    - Can only install one of: guzzlehttp/guzzle[6.5.3, 7.0.1].
    - Can only install one of: guzzlehttp/guzzle[6.5.4, 7.0.1].
    - Can only install one of: guzzlehttp/guzzle[6.5.5, 7.0.1].
    - Installation request for guzzlehttp/guzzle (locked at 7.0.1) -> satisfiable by guzzlehttp/guzzle[7.0.1].

Installation failed, reverting ./composer.json to its original content.

**Comment by josiasmontag** [comment]
Fixed by version 0.6.0

**Comment by sairam2188** [comment]
Thank you.
