### ISSUE TITLE
Update dependency

### ISSUE THREAD

**Issue by JacoboMachado** [josiasmontag/laravel-recaptchav3#16]
Hi Josias,
I pareciate your time to develop this package.
But now I'm trying to update guzzle on my own way and composer response:
>josiasmontag/laravel-recaptchav3 0.3.0 requires guzzlehttp/guzzle ^6.2 -> found guzzlehttp/guzzle[6.2.0, ..., 6.5.x-dev] but it conflicts with your root composer.json require (7.0)

It is possible for you update guzzle? 
Thx

**Comment by josiasmontag** [comment]
PRs are welcome :)

**Comment by JacoboMachado** [comment]
sorry I didn't see that. 
I close this issue and make the pull request. 
thanks
