### ISSUE TITLE
Method 'verify' not found in \Lunaweb\RecaptchaV3\Facades\RecaptchaV3 

### ISSUE THREAD

**Issue by l3keboy** [josiasmontag/laravel-recaptchav3#19]
Getting error: Method 'verify' not found in \Lunaweb\RecaptchaV3\Facades\RecaptchaV3. When trying out the code and dumping the $score variable, I get false, see image: 
![image](https://user-images.githubusercontent.com/66973798/124645068-44c12700-de93-11eb-9afb-e2c23f73709c.png)

can someone help me?

**Comment by l3keboy** [comment]
this is the code: 
![image](https://user-images.githubusercontent.com/66973798/124645121-55719d00-de93-11eb-8c1b-f31a5991affd.png)

**Comment by LoveFromCodes** [comment]
How did you solved this problem please?

**Comment by shoaibgits** [comment]
Any Way to solve this issue?
