### ISSUE TITLE
Non-static method Lunaweb\RecaptchaV3\RecaptchaV3::verify() should not be called statically

### ISSUE THREAD

**Issue by djoey123** [josiasmontag/laravel-recaptchav3#4]
Non-static method Lunaweb\RecaptchaV3\RecaptchaV3::verify() should not be called statically

`$score = RecaptchaV3::verify($request->get('g-recaptcha-response'), 'register');
        var_dump($score);
        die;`

If i use 'g-recaptcha-response' => 'required|recaptchav3:vote,0.5',
I cant post anything, it seems it doesnt detect the module

**Comment by josiasmontag** [comment]
Problem is that you are importing the wrong class, you are trying to use the facade here.
`use Lunaweb\RecaptchaV3\Facade\RecaptchaV3 `

**Comment by djoey123** [comment]
Thank you :)

**Comment by tderick** [comment]
> Problem is that you are importing the wrong class, you are trying to use the facade here. `use Lunaweb\RecaptchaV3\Facade\RecaptchaV3 `

I think it is good to include this in the READ ME file. You didn't give any information on what to include
