### ISSUE TITLE
Class 'App\Http\Controllers\Validator' not found

### ISSUE THREAD

**Issue by KevinMMar98** [josiasmontag/laravel-recaptchav3#9]
I'm new, and I don't know how to import this class to use Validator and RecaptchaV3.
Can you help me please.

**Error:**
Symfony\Component\Debug\Exception\FatalThrowableError
Class 'App\Http\Controllers\Validator' not found

**Comment by linslin** [comment]
`use Illuminate\Support\Facades\Validator;`
